-- Marketing & Promotions: Execute BLOB Deserialization Updates
-- Generated by Python script from all 194 V1 deals
-- This file will be populated by process_all_deals_final.py

-- Summary:
-- - Total deals: 194
-- - Fields deserialized: exceptions, active_days, items
-- - Target columns: exceptions_json, active_days_json, items_json

-- Execute these in batches of 30-40 via Supabase MCP

-- Batch 1 will be generated here...

