UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["92325.1"]'::jsonb WHERE id = 201;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["34693"]'::jsonb WHERE id = 202;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["92441"]'::jsonb WHERE id = 203;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 204;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 205;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["sat"]'::jsonb, items_json = NULL WHERE id = 207;
UPDATE staging.v1_deals SET exceptions_json = '["12929", "884", "767"]'::jsonb, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 209;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu"]'::jsonb, items_json = NULL WHERE id = 211;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 212;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 213;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 214;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 215;
UPDATE staging.v1_deals SET exceptions_json = '["11354", "1325", "1326", "1328", "1329", "1330", "1331", "1332", "1333", "1335", "1336", "13446", "1337", "1338", "2914", "1339"]'::jsonb, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 217;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 218;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 219;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 220;
UPDATE staging.v1_deals SET exceptions_json = '["10134", "10135", "10136"]'::jsonb, active_days_json = '["thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 221;
UPDATE staging.v1_deals SET exceptions_json = '["10141", "10142", "10143"]'::jsonb, active_days_json = '["thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 222;
UPDATE staging.v1_deals SET exceptions_json = '["10141", "10142", "10143", "10144", "10145", "10146"]'::jsonb, active_days_json = '["mon", "tue", "wed"]'::jsonb, items_json = NULL WHERE id = 223;
UPDATE staging.v1_deals SET exceptions_json = '["10134", "10135", "10136", "10137", "10138", "10139"]'::jsonb, active_days_json = '["mon", "tue", "wed"]'::jsonb, items_json = NULL WHERE id = 224;
UPDATE staging.v1_deals SET exceptions_json = '["14354", "14355", "14356"]'::jsonb, active_days_json = '["thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 225;
UPDATE staging.v1_deals SET exceptions_json = '["14354", "14355", "14356", "14357", "14358", "14359"]'::jsonb, active_days_json = '["mon", "tue", "wed"]'::jsonb, items_json = NULL WHERE id = 226;
UPDATE staging.v1_deals SET exceptions_json = '["14347", "14348", "14349"]'::jsonb, active_days_json = '["thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 227;
UPDATE staging.v1_deals SET exceptions_json = '["14347", "14348", "14349", "14350", "14351", "14352"]'::jsonb, active_days_json = '["mon", "tue", "wed"]'::jsonb, items_json = NULL WHERE id = 228;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "sun"]'::jsonb, items_json = '["87158", "87159", "87160", "87163", "87166", "87167"]'::jsonb WHERE id = 229;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = NULL, items_json = NULL WHERE id = 230;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 231;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = NULL, items_json = NULL WHERE id = 232;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["69166.0"]'::jsonb WHERE id = 233;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = NULL, items_json = NULL WHERE id = 234;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = NULL, items_json = NULL WHERE id = 235;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 236;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 237;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 238;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 239;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["104589"]'::jsonb WHERE id = 240;
