UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 129;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 130;
UPDATE staging.v1_deals SET exceptions_json = '["5157", "2892"]'::jsonb, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 131;
UPDATE staging.v1_deals SET exceptions_json = '["5215", "2926"]'::jsonb, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 132;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 133;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["5127"]'::jsonb WHERE id = 134;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["5127"]'::jsonb WHERE id = 135;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 136;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 137;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["4845"]'::jsonb WHERE id = 138;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["5467"]'::jsonb WHERE id = 139;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["5467"]'::jsonb WHERE id = 140;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 141;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 142;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 143;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 144;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 145;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 148;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["62747", "62748"]'::jsonb WHERE id = 149;
UPDATE staging.v1_deals SET exceptions_json = '["6089"]'::jsonb, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 150;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 151;
UPDATE staging.v1_deals SET exceptions_json = '["7837", "7838"]'::jsonb, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["63263"]'::jsonb WHERE id = 152;
UPDATE staging.v1_deals SET exceptions_json = '["7837", "7838"]'::jsonb, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["63263"]'::jsonb WHERE id = 153;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 154;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 155;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 156;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 157;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 158;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 159;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["16145", "30163", "30167", "30171", "16146", "30173", "30176", "16147", "16148", "30177", "16149", "30178", "16150", "30179", "30164"]'::jsonb WHERE id = 160;
