UPDATE staging.v1_deals SET exceptions_json = '["9894", "1079", "1080"]'::jsonb, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 161;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 162;
UPDATE staging.v1_deals SET exceptions_json = '["1101", "1099"]'::jsonb, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 163;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 164;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 165;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 166;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["62382"]'::jsonb WHERE id = 167;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 168;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 169;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 170;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 171;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 172;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["53659"]'::jsonb WHERE id = 174;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["69464"]'::jsonb WHERE id = 176;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["69458"]'::jsonb WHERE id = 177;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["69597"]'::jsonb WHERE id = 178;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["69598"]'::jsonb WHERE id = 179;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["69594"]'::jsonb WHERE id = 180;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["69461"]'::jsonb WHERE id = 181;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 183;
UPDATE staging.v1_deals SET exceptions_json = '["4310", "985", "986", "994", "987", "988", "989", "990", "991", "992", "996", "995", "1414"]'::jsonb, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 187;
UPDATE staging.v1_deals SET exceptions_json = '["6457", "6458", "6459", "6460", "6461", "6462", "7345", "7343", "7344", "7599", "8057", "8058", "6475", "6476", "6496", "6497", "6498", "6499", "6500", "6501", "6502", "6503", "6504", "6505", "6506", "6507", "6508", "6509", "7597", "7598", "6513", "6514", "6517", "7596"]'::jsonb, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 188;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["86581"]'::jsonb WHERE id = 190;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["86582"]'::jsonb WHERE id = 191;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 192;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["11960"]'::jsonb WHERE id = 193;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["11996"]'::jsonb WHERE id = 194;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = '["11977"]'::jsonb WHERE id = 195;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 197;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 198;
UPDATE staging.v1_deals SET exceptions_json = NULL, active_days_json = '["mon", "tue", "wed", "thu", "fri", "sat", "sun"]'::jsonb, items_json = NULL WHERE id = 200;
