-- ============================================================================
-- V2 Phase 1 Import: Load Courses, Dishes, and Prices from JSON files
-- ============================================================================
-- This script reads JSON files generated by v2_scraper_phase1.py and
-- inserts the data into menuca_v3 tables via psql
--
-- Usage:
--   psql "CONNECTION_STRING" -f 01_import_phase1_menus.sql
--
-- Requirements:
--   - JSON files must be in ../phase1_output/ directory
--   - Each file named: restaurant_{id}_menu.json
-- ============================================================================

\set ON_ERROR_STOP on

BEGIN;

-- Create temporary table to hold JSON file data
CREATE TEMP TABLE temp_menu_json (
    restaurant_id BIGINT,
    json_data JSONB
);

-- ============================================================================
-- STEP 1: Load all JSON files into temp table
-- ============================================================================

\echo ''
\echo '================================'
\echo 'Loading JSON files...'
\echo '================================'

-- Note: This will be executed for each restaurant
-- You'll need to run this for each JSON file in the phase1_output directory

-- Example for one restaurant:
-- \set json_file '../phase1_output/restaurant_949_menu.json'
-- INSERT INTO temp_menu_json (restaurant_id, json_data)
-- SELECT 
--     (data->>'db_restaurant_id')::BIGINT,
--     data
-- FROM jsonb_array_elements(pg_read_binary_file(:'json_file')::jsonb) AS data;

\echo 'Note: JSON loading requires custom script per file'
\echo 'See import_phase1_wrapper.sh for automated loading'

-- ============================================================================
-- STEP 2: Insert Courses
-- ============================================================================

\echo ''
\echo '================================'
\echo 'Inserting courses...'
\echo '================================'

WITH course_data AS (
    SELECT
        t.restaurant_id,
        course->>'name' AS course_name,
        COALESCE(course->>'description', '') AS description,
        (course->>'display_order')::INTEGER AS display_order,
        course->>'v2_course_id' AS v2_course_id,
        course AS course_json
    FROM temp_menu_json t,
         jsonb_array_elements(t.json_data->'courses') AS course
)
INSERT INTO menuca_v3.courses (
    restaurant_id,
    name,
    description,
    display_order,
    created_at,
    updated_at
)
SELECT
    restaurant_id,
    course_name,
    description,
    display_order,
    NOW(),
    NOW()
FROM course_data
ON CONFLICT DO NOTHING
RETURNING id, restaurant_id, name;

SELECT COUNT(*) AS courses_inserted FROM menuca_v3.courses WHERE created_at >= NOW() - INTERVAL '1 minute';

-- ============================================================================
-- STEP 3: Insert Dishes
-- ============================================================================

\echo ''
\echo '================================'
\echo 'Inserting dishes...'
\echo '================================'

WITH course_data AS (
    SELECT
        t.restaurant_id,
        course->>'name' AS course_name,
        (course->>'display_order')::INTEGER AS course_display_order,
        dish AS dish_json
    FROM temp_menu_json t,
         jsonb_array_elements(t.json_data->'courses') AS course,
         jsonb_array_elements(course->'dishes') AS dish
),
course_lookup AS (
    SELECT
        c.id AS course_id,
        c.restaurant_id,
        c.name AS course_name,
        c.display_order AS course_display_order
    FROM menuca_v3.courses c
),
dish_data AS (
    SELECT
        cd.restaurant_id,
        cl.course_id,
        cd.dish_json->>'name' AS dish_name,
        COALESCE(cd.dish_json->>'description', '') AS description,
        (cd.dish_json->>'display_order')::INTEGER AS display_order,
        cd.dish_json->>'v2_dish_id' AS v2_dish_id
    FROM course_data cd
    INNER JOIN course_lookup cl 
        ON cd.restaurant_id = cl.restaurant_id 
        AND cd.course_name = cl.course_name 
        AND cd.course_display_order = cl.course_display_order
)
INSERT INTO menuca_v3.dishes (
    restaurant_id,
    course_id,
    name,
    description,
    display_order,
    source_id,
    created_at,
    updated_at
)
SELECT
    restaurant_id,
    course_id,
    dish_name,
    description,
    display_order,
    v2_dish_id,
    NOW(),
    NOW()
FROM dish_data
ON CONFLICT DO NOTHING
RETURNING id, restaurant_id, name, source_id;

SELECT COUNT(*) AS dishes_inserted FROM menuca_v3.dishes WHERE created_at >= NOW() - INTERVAL '1 minute';

-- ============================================================================
-- STEP 4: Insert Dish Prices
-- ============================================================================

\echo ''
\echo '================================'
\echo 'Inserting dish prices...'
\echo '================================'

WITH course_data AS (
    SELECT
        t.restaurant_id,
        course->>'name' AS course_name,
        (course->>'display_order')::INTEGER AS course_display_order,
        dish AS dish_json
    FROM temp_menu_json t,
         jsonb_array_elements(t.json_data->'courses') AS course,
         jsonb_array_elements(course->'dishes') AS dish
),
course_lookup AS (
    SELECT
        c.id AS course_id,
        c.restaurant_id,
        c.name AS course_name,
        c.display_order AS course_display_order
    FROM menuca_v3.courses c
),
dish_lookup AS (
    SELECT
        d.id AS dish_id,
        d.restaurant_id,
        d.course_id,
        d.name AS dish_name,
        d.source_id AS v2_dish_id,
        d.display_order AS dish_display_order
    FROM menuca_v3.dishes d
),
price_data AS (
    SELECT
        dl.dish_id,
        dl.restaurant_id,
        price->>'size_variant' AS size_variant,
        (price->>'price')::NUMERIC(10,2) AS price,
        (price->>'display_order')::INTEGER AS display_order
    FROM course_data cd
    INNER JOIN course_lookup cl 
        ON cd.restaurant_id = cl.restaurant_id 
        AND cd.course_name = cl.course_name 
        AND cd.course_display_order = cl.course_display_order
    INNER JOIN dish_lookup dl
        ON cl.course_id = dl.course_id
        AND cd.dish_json->>'name' = dl.dish_name
        AND (cd.dish_json->>'display_order')::INTEGER = dl.dish_display_order
    CROSS JOIN jsonb_array_elements(cd.dish_json->'prices') AS price
)
INSERT INTO menuca_v3.dish_prices (
    dish_id,
    restaurant_id,
    size_variant,
    price,
    display_order,
    created_at,
    updated_at
)
SELECT
    dish_id,
    restaurant_id,
    size_variant,
    price,
    display_order,
    NOW(),
    NOW()
FROM price_data
ON CONFLICT DO NOTHING
RETURNING id, dish_id, size_variant, price;

SELECT COUNT(*) AS prices_inserted FROM menuca_v3.dish_prices WHERE created_at >= NOW() - INTERVAL '1 minute';

-- ============================================================================
-- Summary
-- ============================================================================

\echo ''
\echo '================================'
\echo 'Import Summary'
\echo '================================'

SELECT
    (SELECT COUNT(*) FROM menuca_v3.courses WHERE created_at >= NOW() - INTERVAL '1 minute') AS courses_imported,
    (SELECT COUNT(*) FROM menuca_v3.dishes WHERE created_at >= NOW() - INTERVAL '1 minute') AS dishes_imported,
    (SELECT COUNT(*) FROM menuca_v3.dish_prices WHERE created_at >= NOW() - INTERVAL '1 minute') AS prices_imported;

COMMIT;

\echo ''
\echo 'Phase 1 import complete!'
\echo ''

